name: Deploy AWS Lambda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Credenciais AWS usando Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::349246405584:role/LabRole
          aws-region: us-east-1

      - name: Configurar Variáveis de Ambiente
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV

      - name: Compilar e Empacotar JAR
        run: |
          mvn clean install -DskipTests
          cp target/auth-lambda-1.0-SNAPSHOT.jar auth-lambda.jar

      - name: Criar ZIP para Lambda
        run: zip -r auth-lambda.zip auth-lambda.jar

      - name: Atualizar AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name minha-lambda \
            --zip-file fileb://auth-lambda.zip
